config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }

  root 'welcome#index'

  resource :welcome, only: :index do
  end

  get 'protected' => 'welcome#protected'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  require 'mixpanel-ruby'
  after_action :identify_mixpanel_id, :only => [:create]

  protected

  def identify_mixpanel_id
    if resource.id?
      tracker = Mixpanel::Tracker.new(ENV['mixpanel_id'])
      tracker.alias(resource.id, JSON.parse(cookies["mp_#{ENV['mixpanel_id']}_mixpanel"])['distinct_id'])
      tracker.people.set(resource.id, {
        '$email'      => resource.email,
        '$signed_up'  => resource.created_at
        });
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  require 'mixpanel-ruby'
  after_action :alias_mixpanel_id, :only => [:create]
  around_action :track_logout, :only => [:destroy]

  protected

  def alias_mixpanel_id
    tracker = Mixpanel::Tracker.new(ENV['mixpanel_id'])
    tracker.track(resource.id, "Signed in")
  end

  def track_logout
    logout_id = current_user.id
    yield
    tracker = Mixpanel::Tracker.new(ENV['mixpanel_id'])
    tracker.track(logout_id, "Signed out")
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, only: :protected

  def index
  end

  def protected
    tracker = Mixpanel::Tracker.new(ENV['mixpanel_id'])
      tracker.track(current_user.id, "Protected Page Visit")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/includes/_tracking.js.erb
<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("<%= ENV['mixpanel_id'] %>", {cross_subdomain_cookie : false});</script><!-- end Mixpanel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mixpaneldemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'https://code.jquery.com/jquery-2.1.3.min.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render '/includes/tracking.js' %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <% if current_user.present? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<% if current_user.present? %>
<h1>Logged in as <%= current_user.email %></h1>
<% else %>
<h1>Welcome to the MixPanel Demo</h1>
<% end %>
<p>Using this App will populate data in Mixpanel. That's about all it will do :)</p>
<h2>Suggested actions</h2>
<ul>
  <li><%= link_to 'Click here', root_path(utm_medium: 'cpc', utm_source: 'adwords', utm_campaign: 'mixpanel', utm_content: 'demo time!') %> to reload page & add Google Analytics campaign data to your session.</li>

  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Visit a restricted page', protected_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
  <li><%= link_to 'See the results', 'https://mixpanel.com/report/565263/events' %> in Mixpanel</li>
  <script>
    mixpanel.track('Homepage Visit');
  </script>

app/views/welcome/protected.html.erb
<h1>Protected Page</h1>